-- Atlante della Rete — spazio personale dello studente
-- Eseguire nel SQL Editor di Supabase.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  created_at timestamptz not null default now()
);

create table if not exists public.bookmarks (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  page_url text not null,
  page_title text,
  created_at timestamptz not null default now(),
  unique(user_id, page_url)
);

create table if not exists public.notes (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  page_url text not null,
  page_title text,
  title text,
  body text not null,
  quote text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.highlights (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  page_url text not null,
  page_title text,
  quote text not null,
  color text not null default 'yellow' check (color in ('yellow','blue','red','green')),
  created_at timestamptz not null default now()
);

create index if not exists highlights_user_page on public.highlights(user_id, page_url);
create index if not exists notes_user_page on public.notes(user_id, page_url);

alter table public.profiles enable row level security;
alter table public.bookmarks enable row level security;
alter table public.notes enable row level security;
alter table public.highlights enable row level security;

create policy "profiles own row" on public.profiles for all using (auth.uid() = id) with check (auth.uid() = id);
create policy "bookmarks own rows" on public.bookmarks for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "notes own rows" on public.notes for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "highlights own rows" on public.highlights for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles(id, display_name) values (new.id, coalesce(new.raw_user_meta_data->>'display_name','')) on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users
for each row execute procedure public.handle_new_user();


create table if not exists public.page_visits (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  page_url text not null,
  page_title text,
  visited_at timestamptz not null default now(),
  unique(user_id, page_url)
);
create index if not exists page_visits_user on public.page_visits(user_id, visited_at desc);
alter table public.page_visits enable row level security;
create policy "page visits own rows" on public.page_visits for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
